name: task_html_lesson_1
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  lints: ^2.0.0
